### ISSUE TITLE
`KeyError: 'Ebs'` when deploying EC2 instance with `ebsBoot`

### ISSUE THREAD

**Issue by ethnt** [NixOS/nixops-aws#156]
When I deploy a new EC2 instance with `ebs` options, I get a `KeyError`:

```
$ nixops deploy --include networking
networking...............> creating EC2 instance (AMI ‘ami-01ac677ff61399caa’, type ‘t3.medium’, region ‘us-east-2’)...
Traceback (most recent call last):
  File "/nix/store/x78r2dz8ynmdz7891m7rm2g552jzrn5s-python3.8-nixops-2.0.0/bin/.nixops-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/__main__.py", line 710, in main
    args.op(args)
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/script_defs.py", line 617, in op_deploy
    depl.deploy(
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/deployment.py", line 1479, in deploy
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/deployment.py", line 1468, in run_with_notify
    f()
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/deployment.py", line 1479, in <lambda>
    self.run_with_notify("deploy", lambda: self._deploy(**kwargs))
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/deployment.py", line 1382, in _deploy
    nixops.parallel.run_tasks(
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/parallel.py", line 106, in run_tasks
    raise list(exceptions.values())[0]
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/parallel.py", line 70, in thread_fun
    work_result = (worker_fun(t), None, t.name)
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops/deployment.py", line 1336, in worker
    r.create(
  File "/nix/store/hwrwb8hfxwcda4zlxqfrzmn7zz22xrmn-python3-3.8.7-env/lib/python3.8/site-packages/nixops_aws/backends/ec2.py", line 1293, in create
    VolumeType=ami["BlockDeviceMappings"][0]["Ebs"]["VolumeType"],
KeyError: 'Ebs'
```

Here's a subset of the configuration I have with NixOps + flakes. I'm using [lukebfox/nixops-plugged](https://github.com/lukebfox/nixops-plugged) but I believe the issue is with `nixops-aws`.

```nix
{
  description = "orchard";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-21.11";
    nixops.url = "github:lukebfox/nixops-plugged";
  };

  outputs = { self, nixpkgs, nixops, ... }@inputs: {
    nixopsConfigurations.default = {
      network = {
        description = "orchard";
        enableRollback = true;
      };

      resources = import ./resources.nix;

      networking = { config, lib, pkgs, resources, ... }: {
        deployment = {
          targetEnv = "ec2";
          ec2 = {
            inherit (aws) region;

            instanceType = "t3.medium";
            keyPair = resources.ec2KeyPairs.deployment-key;
            securityGroups =
              [ resources.ec2SecurityGroups.networking-security-group ];
            ebsBoot = true;
            ebsInitialRootDiskSize = 64;
          };
        };
      };
    };
  };
}
```

**Comment by ethnt** [comment]
Going to close this — I found that I was using an old version of `nixops-aws` and this issue was fixed here: https://github.com/NixOS/nixops-aws/commit/48637acacd3a7d4dd2796df93d6adcf53efdb3fd
